# Generated by Django 6.0.1 on 2026-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WazoUserCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('platform_hostname', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='core_wazous_usernam_b3ee58_idx')],
            },
        ),
    ]
