# Generated by Django 5.2.10 on 2026-01-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wazousercache',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='wazousercache',
            unique_together={('username', 'platform_hostname')},
        ),
    ]
