# Generated by Django 5.2.10 on 2026-01-23 16:19

from django.db import migrations

def create_periodic_tasks(apps, schema_editor):
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    interval, _ = IntervalSchedule.objects.get_or_create(
        every=30,
        period="minutes",
    )

    PeriodicTask.objects.update_or_create(
        name="get_all_wazo_users",
        defaults={
            "task": "core.tasks.get_all_wazo_users",
            "interval": interval,
            "enabled": True,
        },
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_wazousercache_username_and_more'),
        ("django_celery_beat", "__latest__"),
    ]

    operations = [
        migrations.RunPython(create_periodic_tasks),
    ]
